### ISSUE TITLE
Fix asio example

### ISSUE THREAD

**Issue by Warchant** [boostorg/fiber#205] opened 2019-05-17 09:33 UTC
In this commit asio/handler_type.h is removed for asio 1.70.0:

https://github.com/boostorg/asio/commit/b572bfbc217fe51b8d27292042a3db1d1ec4a9c6#diff-2fe8469ef1412ce812cc2703c24c669fL64

But it is still used in asio example `autoecho` 1.70.0:
https://github.com/boostorg/fiber/blob/develop/examples/asio/detail/yield.hpp#L11

UPD: also, I am requesting new example for post 1.70.0 asio. Thanks.

**Comment by olk** [comment] 2019-05-17 09:55
duplicate of  #201

**Closed by olk** 2019-05-17 09:55 UTC
